export const ROUTES = {
  HOME: "/",
  BLOG: "/blog",
  BLOG_DETAILS: "/blog/:slug",
  BOOK_REVIEWS: "/book-reviews",
  ACHIEVEMENTS: "/achievements",
  TRAVEL: "/travel",
  RESEARCH: "/research",
  CONTACT: "/contact",
  PROJECT_DETAILS: "/projects/:slug",
  ADMIN_MESSAGES: "/admin/messages",
  ADMIN_POSTS: "/admin/posts",
  ADMIN_POSTS_NEW: "/admin/posts/new",
  ADMIN_POSTS_EDIT: "/admin/posts/edit/:id",
};